// tailwind.config.ts

import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#a04100",
        "on-primary": "#ffffff",
        "primary-container": "#ff6b00",
        "on-primary-container": "#572000",
        "inverse-primary": "#ffb693",
        "primary-fixed": "#ffdbcc",
        "primary-fixed-dim": "#ffb693",
        "on-primary-fixed": "#351000",
        "on-primary-fixed-variant": "#7a3000",
        secondary: "#006a61",
        "on-secondary": "#ffffff",
        "secondary-container": "#86f2e4",
        "on-secondary-container": "#006f66",
        "secondary-fixed": "#89f5e7",
        "secondary-fixed-dim": "#6bd8cb",
        "on-secondary-fixed": "#00201d",
        "on-secondary-fixed-variant": "#005049",
        tertiary: "#0053db",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#6f94ff",
        "on-tertiary-container": "#002a79",
        "tertiary-fixed": "#dbe1ff",
        "tertiary-fixed-dim": "#b4c5ff",
        "on-tertiary-fixed": "#00174b",
        "on-tertiary-fixed-variant": "#003ea8",
        "on-surface": "#1e1b17",
        "on-surface-variant": "#5a4136",
        "inverse-surface": "#33302b",
        "inverse-on-surface": "#f6f0e8",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        outline: "#8e7164",
        "outline-variant": "#e2bfb0",
        "surface-tint": "#a04100",
        "surface-dim": "#dfd9d2",
        "surface-bright": "#fff8f1",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f9f3eb",
        "surface-container": "#f3ede5",
        "surface-container-high": "#eee7e0",
        "surface-container-highest": "#e8e1da",
        surface: {
          DEFAULT: "#fff8f1",
          dim: "#dfd9d2",
          bright: "#fff8f1",
          canvas: "#F7F7F4",
          card: "#FFFFFF",
          subtle: "#F0EFEA",
        },
        "on-background": "#1e1b17",
        "surface-variant": "#e8e1da",
        background: "#fff8f1",
        "success-emerald": "#059669",
        "success-emerald-subtle": "#ECFDF5",
        "warning-amber": "#D97706",
        "warning-amber-subtle": "#FFFBEB",
        "danger-rose": "#E11D48",
        "danger-rose-subtle": "#FFF1F2",
        "ai-sparkle": "#FF8C38",
        border: {
          subtle: "#E5E4DE",
          strong: "#CDCBC2",
        },
      },
      fontFamily: {
        heading: ["Outfit", "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["40px", { lineHeight: "48px", fontWeight: "700" }],
        "headline-xl-mobile": ["30px", { lineHeight: "38px", fontWeight: "700" }],
        "headline-lg": ["30px", { lineHeight: "38px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-md": ["13px", { lineHeight: "16px", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "600" }],
        "data-tabular": ["13px", { lineHeight: "18px", fontWeight: "500" }],
      },
      letterSpacing: {
        "headline-xl": "0",
        "headline-xl-mobile": "0",
        "headline-lg": "0",
        "headline-lg-mobile": "0",
        "headline-md": "0",
        "headline-sm": "0",
        "body-lg": "0",
        "body-md": "0",
        "body-sm": "0",
        "label-md": "0",
        "label-sm": "0",
        "data-tabular": "0",
      },
      spacing: {
        gutter: "1rem",
        "gutter-desktop": "1.5rem",
        margin: "1rem",
        "margin-tablet": "1.5rem",
        "margin-desktop": "2rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1.25rem",
        "space-xl": "2rem",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      boxShadow: {
        card: "0 1px 3px rgba(20, 18, 14, 0.03), 0 4px 12px rgba(20, 18, 14, 0.02)",
        popover: "0 6px 20px rgba(20, 18, 14, 0.06), 0 2px 6px rgba(20, 18, 14, 0.04)",
        modal: "0 20px 40px -8px rgba(20, 18, 14, 0.14)",
      },
    },
  },
  plugins: [],
};

export default config;